메뉴 선택 및 메뉴 동작 구현
KU-CSE-ITZI/StudentFeeChecker pull request #2
Opened 2024-02-19 17:29 UTC by buzz0331

<추가된 메소드>
-  gotoSelectedMode()는 사용자가 선택한 메뉴에 해당하는 메소드로 이동시켜주는 메소드입니다.
-  CheckValidId()는 스캔/입력받은 학번이 올바른 형식인지 확인해주는 메소드입니다.

문제 사항
1. 현재 바코드 스캔을 할 수 있게 해주는 클래스 사용법을 모르겠어서 Scanner로 처리 해놨습니다.
2. 파일 모드가 정확히 어떤 동작을 하는지 명확하지 않아서 일단 제가 생각한 대로 구현했습니다.
3. StudentFeeRepository의 getStudentInfos()를 어떤 식으로 이용할 생각인지 궁금합니다.

2024-02-20 01:43 UTC, Ji-InPark requested changes
일단 간단하게 리뷰했습니다. 
리뷰 반영 부탁드릴게요.

2024-02-20 01:43 UTC, Ji-InPark commented on src/service/StudentFeeService.java
> +        }
else if 를 사용해야 하는 경우면 대부분 switch 문으로 바꾸는게 더 좋습니다.

2024-02-20 01:43 UTC, Ji-InPark commented on src/service/StudentFeeService.java
> +    private boolean CheckValidId(String sid){
java에서 메소드는 camel case를 사용합니다.

2024-02-20 01:43 UTC, Ji-InPark commented on src/service/StudentFeeService.java
> +        else if(StudentFeeRepository.getInstance().getStudentInfo(sid)==null){
굳이 else if일 필요 없이 if 여도 되는 부분입니다.

2024-02-20 01:43 UTC, Ji-InPark commented on src/service/StudentFeeService.java
> +        }
if문에 로직을 이렇게 작성하면 어떤것을 하고 있는건지 확인하기 힘듭니다.
validateStudentId와 같은 메소드로 추출하는 것도 나쁘지 않을 것 같네요.
또한 이럴 때는 regex를 사용하는 것도 좋습니다.

2024-02-20 01:43 UTC, Ji-InPark commented on src/service/StudentFeeService.java
> +        String id;
id 변수가 여기 선언될 필요가 없이 while문 안에서 선언되어도 괜찮을 것 같습니다.

2024-02-20 01:43 UTC, Ji-InPark commented on src/service/StudentFeeService.java
> +                    System.out.println("메뉴로 돌아갑니다.");
현 동작으로 보면 메뉴로 돌아가지 않고 프로그램이 끝날 것으로 보이는데 맞나요?

2024-02-20 01:43 UTC, Ji-InPark commented on src/service/StudentFeeService.java
> +            }
납부 여부는 나중에 더 알아보기 쉬운 형태로 변경이 필요할 것 같네요.
일단은 유지하셔도 됩니다.

2024-02-20 01:43 UTC, Ji-InPark commented on src/service/StudentFeeService.java
> +        }
파일 모드 파일을 읽어서 처리하기 때문에 scanner를 사용하지 않습니다.
일단 이 부분 구현은 하지 마시죠

2024-02-21 01:27 UTC, Ji-InPark reviewed
전체적으로 잘 반영해주셨네요.
이제는 제가 남긴 리뷰 하나당 커밋을 작성한다는 느낌으로 커밋을 나누는 연습을 해보시면 좋을 것 같습니다!

2024-02-21 01:27 UTC, Ji-InPark commented on src/service/StudentFeeService.java
> +            }
이 부분도 메소드로 만들면 코드가 더 읽기 좋을 것 같네요

2024-02-21 01:27 UTC, Ji-InPark commented on src/service/StudentFeeService.java
> +            }
그런데 다시 생각해보니 학번을 검사해야하는 이유가 있나요??
어차피 repository에서 찾아지지 않는다면 존재하지 않는 학번인 것이니 문제 없을 것 같아서요!

2024-02-21 01:27 UTC, Ji-InPark commented on src/service/StudentFeeService.java
> +        if(StudentFeeRepository.getInstance().getStudentInfo(sid)==null){
또한 student info 객체를 가져와서 valid한지 check만하고, 나중에 한 번 더 call하는건 비효율 적인 것 같습니다.
차라리 학번이 없을 때 repository에서 exception을 일으키게 하는 방식으로 코드를 짜는게 더 좋을 것 같아요

2024-02-21 01:27 UTC, Ji-InPark commented on src/service/StudentFeeService.java
> +            } while (!checkValidId(id));
여기서도 white true로 바꾸고 계속 입력 받아도 괜찮을 것 같아요.
어차피 q를 입력받으면 끝나게 되어있으니깐요

2024-02-21 01:27 UTC, Ji-InPark commented on src/service/StudentFeeService.java
> +    private boolean checkValidId(String sid){
sid 처럼 줄이는 것보다는 id, studentId 와 같이 사용하는게 좋습니다.

2024-02-23 16:07 UTC, Ji-InPark requested changes
리뷰가 아닌 질문일 때는 질문에 대한 답을 해주고 resolve는 질문자에게 맡겨주세요!

2024-02-23 16:07 UTC, Ji-InPark commented on src/repository/StudentFeeRepository.java
> +        System.out.println("일치하는 학번이 존재하지 않습니다.");
map에는 containsKey라는 메소드가 있습니다.
이 메소드는 O(1)의 시간복잡도를 가지는 매우 빠른 메소드이니 검색후 적용해주세요!

2024-02-23 16:07 UTC, Ji-InPark commented on src/repository/StudentFeeRepository.java
> +        System.out.println("일치하는 학번이 존재하지 않습니다.");
또한 containsKey말고 그냥 getOrDefault를 사용가능할 수 있으니 한 번 확인해보세요!

2024-02-23 16:07 UTC, Ji-InPark commented on src/service/StudentFeeService.java
> +    private void gotoSelectedMode(Mode mode) {
goto 보다는 start가 더 맞을 것 같습니다!

2024-02-23 16:07 UTC, Ji-InPark commented on src/service/StudentFeeService.java
> +                break Select;
나가는 거라면 gotoSelectedMode 보다 위에 쓰고 gotoSelectedMode 안에서는 exit를 처리하지 않아도 될 것 같습니다!

2024-02-23 16:07 UTC, Ji-InPark commented on src/service/StudentFeeService.java
> +                    System.out.println("메뉴로 돌아갑니다.");
리뷰에 답장을 하지 않으시고 resolve하시면 안됩니다!
이렇게 질문식의 리뷰에서는 답변 후 질문자가 resolve하게끔 해주세요!

2024-02-23 16:07 UTC, Ji-InPark commented on src/service/StudentFeeService.java
> +        StudentInfo student;
student가 while문 밖에 있어야할 이유가 없습니다!

2024-02-23 16:07 UTC, Ji-InPark commented on src/service/StudentFeeService.java
> +            } while (student == null);
굳이 do while을 사용할 필요가 없는 부분입니다.
student가 null일 때는 continue를 해도 됩니다.

2024-02-24 12:27 UTC, buzz0331 commented on src/service/StudentFeeService.java
> +                break Select;
startSelectedMode() 메소드 안에 exit도 가능하게 한 이유는 처음 코드를 받았을 때 enum인 Mode안에 EXIT이 포함되어 있어서 EXIT도 하나의 Mode로 생각하고 가독성을 높이고자 코드를 저렇게 작성하였습니다. 그냥 수정할까요?

2024-02-24 12:28 UTC, buzz0331 commented on src/service/StudentFeeService.java
> +        StudentInfo student;
이 부분을 빼고 커밋해서 다른 커밋보시면 변경되어 있습니다!

2024-02-24 12:33 UTC, buzz0331 commented on src/service/StudentFeeService.java
> +                    System.out.println("메뉴로 돌아갑니다.");
<img width="177" alt="스크린샷 2024-02-24 오후 9 33 41" src="https://github.com/KU-CSE-ITZI/StudentFeeChecker/assets/130340360/97fe0ba9-619a-4b7d-8643-6d35747d5d1f">
이렇게 메뉴로 돌아가게 됩니다!

2024-02-24 15:09 UTC, Ji-InPark commented on src/service/StudentFeeService.java
> +                break Select;
enum에 exit가 포함되어 있어도 어차피 따로 처리를 해줘야 하는 상황이니 굳이 저 메소드에 책임을 넘길필요가 없습니다!
또한 위치가 바뀐다고 해서 큰게 가독성에 문제는 없을 것 같습니다!

2024-02-24 15:12 UTC, Ji-InPark approved these changes
주석만 지우고 이제 머지해봐도 좋을 것 같습니다!
수고하셨습니다!

2024-02-24 15:12 UTC, Ji-InPark commented on src/repository/StudentFeeRepository.java
> +//        }
넵 이건 이제 지워주셔도 됩니다!

2024-02-25 02:18 UTC, merged